services:
  nutrimenuenterprise:
    build:
      context: ../webapps/NutriMenuEnterprise
    restart: always
    ports:
      - 8081:8080
    networks:
      - nutrimenu-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/nutri_db?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - nutrimenu-net
    environment:
      MYSQL_DATABASE: nutri_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  nutrimenu-net:
